all: cm
cm:
	python plotConfussionMatrics.py \
		--metrics_file ../outputs/20220907205652_DigitMNIST_2/results/metrics.json \
		--out_files_directory_path ../outputs/20220907205652_DigitMNIST_2/results/confussion_metrics/ \
		--config_file ../outputs/20220907205652_DigitMNIST_2/config.json